# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f857adfd8c13df6906a6b590e453678b221f7ed97f8b0f79a011825985472dae6031666beba2ce694ab6a14dbcac58e391411af44c9e6507953791783fee75a7

test:
  secret_key_base: 61e72b41e2718b21e566f00a017f02b70336f3fe0587448d7702762f000b84c9abbe5adc621532006a4252de88f09b0735f1fb665fc263af9ae0f8131f1a2c03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
